services:
  php:
    build:
      context: ./simple-products-ddd
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./simple-products-ddd:/var/www/html
    networks:
      - ddd-network
  mysql:
    image: mysql:8.0
    container_name: ddd-mysql
    ports:
      - "3307:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_products_ddd
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./simple-products-ddd/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db_data:/var/lib/mysql
    networks:
      - ddd-network
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    container_name: nginx-container
    ports:
      - 8080:80
    networks:
      - ddd-network

networks:
    ddd-network:
        driver: bridge

volumes:
    db_data: